### PR TITLE
Integration of social sign in using firebase in lead-management-server

### PR DESCRIPTION
**Pull request by w0lF07**
Added the authentication support of login through Google. Facebook, twitter, github, etc can also be added.

Add the configuration for your Firebase project to the public/js/config.js file

### CODE REVIEW

**Comment by SachinRammoorthy** [comment]
@w0lF07 I can't help but notice that your code is exactly similar to [mine](https://github.com/jboss-outreach/lead-management-server/pull/10), including changes that I made later. In the spirit of the competition, would you mind creating your own code please?

**Comment by w0lF07** [comment]
Please can you allow me to copy the code, please?

**Comment by SachinRammoorthy** [comment]
I'm sorry, but you cannot just copy code! Even if I was OK with it (I am not), the mentors would not be OK. Try to come up with your own code.

**Comment by w0lF07** [comment]
Bro are you a participant of this competition or a mentor???

**Comment by SachinRammoorthy** [comment]
I am a participant

**Pull request closed without merging**
